# ansible/playbook.yml
---
- name: Setup App and Support Servers
  hosts: all
  become: true
  tasks:
    - name: Update system packages using dnf
      dnf:
        name: "*"
        state: latest
        update_cache: yes

- name: Setup App Server
  hosts: appserver
  become: true
  tasks:
    - name: Install Docker and Git
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - git

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        tar xvfz node_exporter-1.7.0.linux-amd64.tar.gz
        sudo mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
        rm -rf node_exporter-1.7.0.linux-amd64*
      args:
        creates: /usr/local/bin/node_exporter

    - name: Create Node Exporter service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: true
        state: started

    - name: Clone GitHub repository
      git:
        repo: "https://github.com/Venanciusnimitha/your-repo.git"
        dest: /home/ec2-user/app

    - name: Build Docker image
      command: docker build -t my-app /home/ec2-user/app

    - name: Run Docker container
      command: docker run -d -p 80:80 my-app

- name: Setup Support Server
  hosts: supportserver
  become: true
  tasks:
    - name: Install Prometheus and Grafana
      dnf:
        name:
          - prometheus
          - grafana
        state: present

    - name: Configure Prometheus
      copy:
        src: ./prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Restart and enable Prometheus
      systemd:
        name: prometheus
        enabled: true
        state: restarted

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: true
        state: started

